name: model_train
permissions:
  id-token: write
  contents: write

on:
  - push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          cd MLOps
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install cml
          
        shell: /usr/bin/bash -e {0}
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.8.18/x64
          PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.8.18/x64/lib/pkgconfig
          Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.18/x64
          Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.18/x64
          Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.18/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.18/x64/lib
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.PAT }}
        run: |
          cd MLOps
          python train_model.py
          python test.py
          
          echo "# Sanity Checks" > report2.md
          cat test.txt >> report2.md
          
          echo "# Decision Tree Model Scores" > report.md
          cat scores.txt >> report.md
          
          echo "# Confusion Matrix & Feature Importance" > report1.md
          echo '![](./ConfusionMatrix.png "ConfusionMatrix")' >> report1.md
          echo '![](./FeatureImportance.png "FeatureImportance")' >> report1.md
          
          cat report2.md report.md report1.md > combined_file.md
          cml comment create combined_file.md
